service: lambda-wikipedia-search

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  lambda_handler:
    handler: handler.lambda_handler

plugins:
  - serverless-python-requirements
